// Code generated by gen/generate.go — DO NOT EDIT.
// Re-run: go run gen/generate.go

package rail0

import (
	"context"
	"fmt"
	"net/url"
)

// AccountsService exposes account configuration operations.
type AccountsService struct {
	http *httpClient
}

// PaymentMethodsFilters holds optional filters for PaymentMethods.
type PaymentMethodsFilters struct {
	StablecoinID     string // filter by token id
	StablecoinSymbol string // filter by token symbol (case-insensitive)
	BlockchainID     string // filter by blockchain id
	BlockchainSlug   string // filter by blockchain slug (case-insensitive)
}

// PaymentMethods returns the active payment methods (chain + token + wallet) for the given account.
// All non-empty filter fields are applied as AND conditions; discordant filters return an empty slice.
func (s *AccountsService) PaymentMethods(ctx context.Context, accountID string, filters ...PaymentMethodsFilters) ([]PaymentMethod, error) {
	var out []PaymentMethod
	path := fmt.Sprintf("/accounts/%s/payment-methods", accountID)

	if len(filters) > 0 {
		f := filters[0]
		q := url.Values{}
		if f.StablecoinID != "" {
			q.Set("stablecoin_id", f.StablecoinID)
		}
		if f.StablecoinSymbol != "" {
			q.Set("stablecoin_symbol", f.StablecoinSymbol)
		}
		if f.BlockchainID != "" {
			q.Set("blockchain_id", f.BlockchainID)
		}
		if f.BlockchainSlug != "" {
			q.Set("blockchain_slug", f.BlockchainSlug)
		}
		if len(q) > 0 {
			path = path + "?" + q.Encode()
		}
	}

	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ListWalletsParams holds optional query parameters for Wallets.
type ListWalletsParams struct {
	ChainID     int    // filter by EVM chain ID (0 = no filter)
	ChainSlug   string // filter by chain slug (e.g. "base")
	TokenSymbol string // filter by token symbol (e.g. "USDC")
	Active      *bool  // filter by active flag; nil = no filter
	Page        int    // page number (1-based); 0 = use server default
	PerPage     int    // items per page; 0 = use server default
}

// Wallets lists the wallet tokens for the given account.
func (s *AccountsService) Wallets(ctx context.Context, accountID string, params ...ListWalletsParams) (*PaginatedResponse[WalletToken], error) {
	var out PaginatedResponse[WalletToken]
	path := fmt.Sprintf("/accounts/%s/wallets", accountID)

	if len(params) > 0 {
		p := params[0]
		q := url.Values{}
		if p.ChainID != 0 {
			q.Set("chain_id", fmt.Sprintf("%d", p.ChainID))
		}
		if p.ChainSlug != "" {
			q.Set("chain_slug", p.ChainSlug)
		}
		if p.TokenSymbol != "" {
			q.Set("token_symbol", p.TokenSymbol)
		}
		if p.Active != nil {
			if *p.Active {
				q.Set("active", "true")
			} else {
				q.Set("active", "false")
			}
		}
		if p.Page > 0 {
			q.Set("page", fmt.Sprintf("%d", p.Page))
		}
		if p.PerPage > 0 {
			q.Set("per_page", fmt.Sprintf("%d", p.PerPage))
		}
		if len(q) > 0 {
			path = path + "?" + q.Encode()
		}
	}

	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Wallet fetches a single wallet token by id for the given account.
func (s *AccountsService) Wallet(ctx context.Context, accountID string, walletID string) (*WalletToken, error) {
	var out WalletToken
	path := fmt.Sprintf("/accounts/%s/wallets/%s", accountID, walletID)
	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
