// Code generated by gen/generate.go — DO NOT EDIT.
// Re-run: go run gen/generate.go

package rail0

import "context"

// ChainsService exposes the supported blockchain catalog.
type ChainsService struct {
	http *httpClient
}

// Blockchain is a supported EVM chain.
type Blockchain struct {
	ChainID     int    `json:"chain_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	NetworkType string `json:"network_type"`
	ExplorerURL string `json:"explorer_url"`
}

// List returns all active blockchains.
func (s *ChainsService) List(ctx context.Context) ([]Blockchain, error) {
	var out []Blockchain
	if err := s.http.get(ctx, "/blockchains", &out); err != nil {
		return nil, err
	}
	return out, nil
}
