// Code generated by gen/generate.go — DO NOT EDIT.
// Re-run: go run gen/generate.go

package rail0

import "context"

// ChainsService exposes the supported blockchain catalog.
type ChainsService struct {
	http *httpClient
}

// Blockchain is a supported EVM chain.
type Blockchain struct {
	ID           string `json:"id"`
	ChainID      int    `json:"chain_id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	NativeSymbol string `json:"native_symbol"`
	NetworkType  string `json:"network_type"`
	RpcURL       string `json:"rpc_url"`
	ExplorerURL  string `json:"explorer_url"`
	Active       bool   `json:"active"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// List returns all active blockchains.
func (s *ChainsService) List(ctx context.Context) ([]Blockchain, error) {
	var out []Blockchain
	if err := s.http.get(ctx, "/blockchains", &out); err != nil {
		return nil, err
	}
	return out, nil
}
