// Code generated by gen/generate.go — DO NOT EDIT.
// Re-run: go run gen/generate.go

package rail0

import (
	"context"
	"fmt"
	"net/url"
)

// PaymentsService implements the payment lifecycle operations.
type PaymentsService struct {
	http *httpClient
}

// ListPaymentsParams holds optional query parameters for Payments.List.
type ListPaymentsParams struct {
	Status  string // filter by payment status
	Mode    string // filter by mode ("authorize" or "charge")
	Payer   string // filter by payer Ethereum address
	Payee   string // filter by payee Ethereum address
	Token   string // filter by token contract address
	Page    int    // page number (1-based); 0 = use server default
	PerPage int    // items per page; 0 = use server default
}

// List returns payments for the authenticated wallet (requires JWT).
func (s *PaymentsService) List(ctx context.Context, params ...ListPaymentsParams) (*PaginatedResponse[PaymentSummary], error) {
	var out PaginatedResponse[PaymentSummary]
	path := "/payments"

	if len(params) > 0 {
		p := params[0]
		q := url.Values{}
		if p.Status != "" {
			q.Set("status", p.Status)
		}
		if p.Mode != "" {
			q.Set("mode", p.Mode)
		}
		if p.Payer != "" {
			q.Set("payer", p.Payer)
		}
		if p.Payee != "" {
			q.Set("payee", p.Payee)
		}
		if p.Token != "" {
			q.Set("token", p.Token)
		}
		if p.Page > 0 {
			q.Set("page", fmt.Sprintf("%d", p.Page))
		}
		if p.PerPage > 0 {
			q.Set("per_page", fmt.Sprintf("%d", p.PerPage))
		}
		if len(q) > 0 {
			path = path + "?" + q.Encode()
		}
	}

	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create creates a payment intent and returns the EIP-712 signingPayload for the payer to sign.
func (s *PaymentsService) Create(ctx context.Context, params CreatePaymentRequest) (*CreatePaymentResponse, error) {
	var out CreatePaymentResponse
	if err := s.http.post(ctx, "/payments", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePayment is an alias for Create for backward compatibility.
func (s *PaymentsService) CreatePayment(ctx context.Context, params CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return s.Create(ctx, params)
}

// Get fetches the current payment state (DB status + live on-chain amounts).
func (s *PaymentsService) Get(ctx context.Context, paymentID Bytes32) (*PaymentSummary, error) {
	var out PaymentSummary
	if err := s.http.get(ctx, "/payments/"+paymentID, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTransactionsParams holds optional query parameters for Payments.Transactions.
type ListTransactionsParams struct {
	Operation string // filter by operation type
	Status    string // filter by transaction status
	Page      int    // page number (1-based); 0 = use server default
	PerPage   int    // items per page; 0 = use server default
}

// Transactions lists on-chain transactions for a payment.
func (s *PaymentsService) Transactions(ctx context.Context, paymentID Bytes32, params ...ListTransactionsParams) (*PaginatedResponse[TransactionRecord], error) {
	var out PaginatedResponse[TransactionRecord]
	path := fmt.Sprintf("/payments/%s/transactions", paymentID)

	if len(params) > 0 {
		p := params[0]
		q := url.Values{}
		if p.Operation != "" {
			q.Set("operation", p.Operation)
		}
		if p.Status != "" {
			q.Set("status", p.Status)
		}
		if p.Page > 0 {
			q.Set("page", fmt.Sprintf("%d", p.Page))
		}
		if p.PerPage > 0 {
			q.Set("per_page", fmt.Sprintf("%d", p.PerPage))
		}
		if len(q) > 0 {
			path = path + "?" + q.Encode()
		}
	}

	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Sign deposits the payer's EIP-712 signature. params.Signature must be the
// 65-byte secp256k1 signature as a 0x-prefixed 130-char hex string (r+s+v).
func (s *PaymentsService) Sign(ctx context.Context, paymentID Bytes32, params PayerSignatureRequest) (*PayerSignatureResponse, error) {
	var out PayerSignatureResponse
	if err := s.http.put(ctx, "/payments/"+paymentID+"/sign", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Authorize ──────────────────────────────────────────────────────────────────

// AuthorizePrepare builds the unsigned authorize() transaction.
func (s *PaymentsService) AuthorizePrepare(ctx context.Context, paymentID Bytes32) (*PrepareTransactionResponse, error) {
	var out PrepareTransactionResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/authorize/prepare", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Authorize submits the signed authorize transaction for asynchronous broadcast.
func (s *PaymentsService) Authorize(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/authorize", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Charge ─────────────────────────────────────────────────────────────────────

// ChargePrepare builds the unsigned charge() transaction (one-shot authorize+capture).
func (s *PaymentsService) ChargePrepare(ctx context.Context, paymentID Bytes32) (*PrepareTransactionResponse, error) {
	var out PrepareTransactionResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/charge/prepare", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Charge submits the signed charge transaction. Poll Get until "charged".
func (s *PaymentsService) Charge(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/charge", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Capture ────────────────────────────────────────────────────────────────────

// CapturePrepare builds the unsigned capture() transaction.
func (s *PaymentsService) CapturePrepare(ctx context.Context, paymentID Bytes32, params CapturePaymentRequest) (*PrepareTransactionResponse, error) {
	var out PrepareTransactionResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/capture/prepare", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Capture submits the signed capture transaction. Poll Get until "captured".
func (s *PaymentsService) Capture(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/capture", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Void ───────────────────────────────────────────────────────────────────────

// VoidPrepare builds the unsigned void() transaction.
func (s *PaymentsService) VoidPrepare(ctx context.Context, paymentID Bytes32) (*PrepareTransactionResponse, error) {
	var out PrepareTransactionResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/void/prepare", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Void submits the signed void transaction. Poll Get until "voided".
func (s *PaymentsService) Void(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/void", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Release ────────────────────────────────────────────────────────────────────

// ReleasePrepare builds the unsigned release() transaction.
func (s *PaymentsService) ReleasePrepare(ctx context.Context, paymentID Bytes32, params ReleaseRequest) (*PrepareTransactionResponse, error) {
	var out PrepareTransactionResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/release/prepare", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Release submits the signed release transaction. Poll Get until "released".
func (s *PaymentsService) Release(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/release", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ── Refund (EIP-3009) ─────────────────────────────────────────────────────────

// RefundPrepare is a two-phase endpoint that builds the unsigned refund() transaction.
func (s *PaymentsService) RefundPrepare(ctx context.Context, paymentID Bytes32, params RefundPayloadRequest) (*RefundPayloadResponse, error) {
	var out RefundPayloadResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/refund/prepare", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Refund submits the signed refund transaction. Poll Get until "refunded".
func (s *PaymentsService) Refund(ctx context.Context, paymentID Bytes32, params SubmitTransactionRequest) (*SubmitTransactionAcceptedResponse, error) {
	var out SubmitTransactionAcceptedResponse
	if err := s.http.post(ctx, "/payments/"+paymentID+"/refund", params, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
