// Code generated by gen/generate.go — DO NOT EDIT.
// Re-run: go run gen/generate.go

package rail0

import (
	"context"
	"strconv"
)

// TokensService exposes the supported token catalog.
type TokensService struct {
	http *httpClient
}

// Token is a supported ERC-20 token on a specific chain.
type Token struct {
	ChainID   int     `json:"chain_id"`
	ChainSlug string  `json:"chain_slug"`
	Symbol    string  `json:"symbol"`
	Address   Address `json:"address"`
	Decimals  int     `json:"decimals"`
}

// List returns all active tokens. Pass chainID > 0 to filter by chain.
func (s *TokensService) List(ctx context.Context, chainID int) ([]Token, error) {
	var out []Token
	path := "/tokens"
	if chainID > 0 {
		path += "?chain_id=" + strconv.Itoa(chainID)
	}
	if err := s.http.get(ctx, path, &out); err != nil {
		return nil, err
	}
	return out, nil
}
