// Code generated by gen/generate.go on 2026-06-03 21:44:30 UTC; DO NOT EDIT.
// Source: rail0-api/docs/openapi.json
//
// To regenerate after changing the OpenAPI spec:
//   go run gen/generate.go

package rail0

// Address is a type alias for string. EVM address (checksummed or lowercase hex, 20 bytes).
type Address = string

// Bytes32 is a type alias for string. 32-byte hex value.
type Bytes32 = string

// Uint256String is a type alias for string. Non-negative integer encoded as a decimal string to avoid JSON numeric precision loss.
type Uint256String = string

// Account A RAIL0 merchant account.
type Account struct {
	Active bool `json:"active"`
	CreatedAt string `json:"created_at"`
	Email string `json:"email"`
	Id string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	FeeBps *int `json:"fee_bps,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}

// CapturePaymentRequest Amount to capture from escrow. May be less than `capturable_amount` for a partial capture.
type CapturePaymentRequest struct {
	// Amount to capture (in token base units). Must be > 0 and <= current capturable_amount.
	Amount Uint256String `json:"amount"`
}

// ConfirmTransactionRequest Payload sent by the rail0-indexer when an on-chain event is detected for a known transaction.
type ConfirmTransactionRequest struct {
	// Block number in which the transaction was confirmed.
	BlockNumber int `json:"block_number"`
	// The on-chain event emitted by the RAIL0 contract.
	EventType string `json:"event_type"`
	// The rail0_id of the payment this transaction belongs to.
	PaymentId Bytes32 `json:"payment_id"`
	// Token amount from the on-chain event. Required for `captured` and `refunded` events; optional for others.
	Amount *Uint256String `json:"amount,omitempty"`
}

// CreatePaymentRequest Parameters needed to create a payment intent.
type CreatePaymentRequest struct {
	// EVM chain ID of the target network.
	ChainId int `json:"chain_id"`
	Payment PaymentInput `json:"payment"`
	// Optional human-readable payment label visible to the payer (e.g. "Order #123 — Acme Store").
	Description string `json:"description,omitempty"`
	// Arbitrary key-value data for custom reconciliation. Set at creation and immutable. Max 4 KB.
	Metadata *any `json:"metadata,omitempty"`
	// `authorize` — funds held in escrow, captured later. `charge` — one-shot: funds immediately distributed. The two modes use different EIP-3009 nonce prefixes; a signature for one cannot be reused for the other.
	Mode string `json:"mode,omitempty"`
}

// CreatePaymentResponse
type CreatePaymentResponse struct {
	ChainId int `json:"chain_id"`
	// EIP-712 hash of the Payment struct. Commits the signature to the exact payment terms.
	ConfigHash Bytes32 `json:"config_hash"`
	Payment PaymentConfig `json:"payment"`
	// Address of the RAIL0 contract on the target chain.
	Rail0Contract Address `json:"rail0_contract"`
	// Unique identifier for this payment.
	Rail0Id Bytes32 `json:"rail0_id"`
	SigningPayload SigningPayload `json:"signing_payload"`
	// Optional human-readable payment label.
	Description string `json:"description,omitempty"`
	// Arbitrary key-value data attached at creation for custom reconciliation.
	Metadata *any `json:"metadata,omitempty"`
}

// EIP3009Message Message fields for the EIP-3009 TransferWithAuthorization signature.
type EIP3009Message struct {
	From Address `json:"from"`
	// keccak256(NONCE_PREFIX, rail0_id, config_hash). Binds the signature to the exact config and operation type.
	Nonce Bytes32 `json:"nonce"`
	// RAIL0 contract address.
	To Address `json:"to"`
	// Always '0' for RAIL0 flows.
	ValidAfter Uint256String `json:"validAfter"`
	// Equals authorization_expiry.
	ValidBefore Uint256String `json:"validBefore"`
	Value Uint256String `json:"value"`
}

// EIP712Domain EIP-712 domain for the token contract.
type EIP712Domain struct {
	ChainId int `json:"chainId"`
	Name string `json:"name"`
	// Token contract address.
	VerifyingContract Address `json:"verifyingContract"`
	Version string `json:"version"`
}

// Error
type Error struct {
	// Machine-readable error code (snake_case).
	Code string `json:"code"`
	// Human-readable error description.
	Message string `json:"message"`
}

// GetPaymentResponse Current state of a payment record.
type GetPaymentResponse struct {
	Amount Uint256String `json:"amount"`
	AuthorizationExpiry int64 `json:"authorization_expiry"`
	ChainId int `json:"chain_id"`
	Mode string `json:"mode"`
	Payee Address `json:"payee"`
	Payer Address `json:"payer"`
	Rail0Id Bytes32 `json:"rail0_id"`
	RefundExpiry int64 `json:"refund_expiry"`
	// Current lifecycle state.
	Status string `json:"status"`
	Token Address `json:"token"`
	// Optional human-readable payment label.
	Description string `json:"description,omitempty"`
	// Machine-readable failure reason. Present only when status=failed.
	FailureCode string `json:"failure_code,omitempty"`
	// Human-readable failure description. Present only when status=failed.
	FailureMessage string `json:"failure_message,omitempty"`
	// Hash of the most recently broadcast transaction.
	LastBroadcastHash *Bytes32 `json:"last_broadcast_hash,omitempty"`
	// Arbitrary key-value data attached at creation for custom reconciliation.
	Metadata *any `json:"metadata,omitempty"`
	// Live on-chain amounts. Present when status is authorized, captured, voided, released, charged, or refunded.
	OnChain *any `json:"on_chain,omitempty"`
}

// PayerSignatureRequest EIP-712 signature over the `signing_payload` returned by `POST /payments`.
type PayerSignatureRequest struct {
	// 65-byte secp256k1 signature (0x-prefixed, 132 chars): r (32 bytes) + s (32 bytes) + v (1 byte).
	Signature string `json:"signature"`
}

// PayerSignatureResponse
type PayerSignatureResponse struct {
	Rail0Id Bytes32 `json:"rail0_id"`
	// The address recovered from the signature — should match `payment.payer`.
	RecoveredPayer Address `json:"recovered_payer"`
	// Confirms the signature was accepted and stored.
	Status string `json:"status"`
}

// PaymentConfig Immutable payment configuration that maps 1-to-1 to the RAIL0 `Payment` Solidity struct.
type PaymentConfig struct {
	// Exact amount the payer commits to pay (in token base units).
	Amount Uint256String `json:"amount"`
	// Unix timestamp (seconds). Capture must happen before this; release opens after.
	AuthorizationExpiry int64 `json:"authorization_expiry"`
	// Fee in basis points (0 = no fee, 10000 = 100%).
	FeeBps int `json:"fee_bps"`
	// Recipient of the fee on each capture. Use the zero address when fee_bps is 0.
	FeeReceiver Address `json:"fee_receiver"`
	// Account address. Authorized to capture, void, and refund.
	Payee Address `json:"payee"`
	// Buyer address. Funds are pulled from this address.
	Payer Address `json:"payer"`
	// Unix timestamp (seconds). Refund must happen before this. Must be >= authorization_expiry.
	RefundExpiry int64 `json:"refund_expiry"`
	// EIP-3009-capable ERC-20 token address (must be accepted by the RAIL0 deployment).
	Token Address `json:"token"`
}

// PaymentInput Buyer-supplied payment parameters. Policy fields (authorization_expiry, refund_expiry, fee_bps, fee_receiver) are fixed API configuration applied server-side.
type PaymentInput struct {
	// Amount to pay (in token base units).
	Amount Uint256String `json:"amount"`
	// Account wallet address (wallet_address from GET /accounts/{id}/payment-methods).
	Payee Address `json:"payee"`
	// Buyer address. Funds are pulled from this address.
	Payer Address `json:"payer"`
	// ERC-20 token address (token_address from GET /accounts/{id}/payment-methods).
	Token Address `json:"token"`
}

// PaymentMethod A single accepted payment method for a account: one (chain, token, wallet) combination.
type PaymentMethod struct {
	ChainId int `json:"chain_id"`
	ChainName string `json:"chain_name"`
	Default bool `json:"default"`
	Id int `json:"id"`
	// ERC-20 token contract address on the chain.
	TokenAddress Address `json:"token_address"`
	TokenDecimals int `json:"token_decimals"`
	TokenId int `json:"token_id"`
	TokenSymbol string `json:"token_symbol"`
	// Account wallet address to use as `payee` in PaymentConfig.
	WalletAddress Address `json:"wallet_address"`
}

// PaymentSummary Condensed payment record returned by GET /payments.
type PaymentSummary struct {
	Amount string `json:"amount"`
	AuthorizationExpiry int `json:"authorization_expiry"`
	CreatedAt string `json:"created_at"`
	Mode string `json:"mode"`
	Payee Address `json:"payee"`
	Payer Address `json:"payer"`
	Rail0Id Bytes32 `json:"rail0_id"`
	RefundExpiry int `json:"refund_expiry"`
	Status string `json:"status"`
	Token Address `json:"token"`
	Description string `json:"description,omitempty"`
	Metadata *any `json:"metadata,omitempty"`
}

// PrepareTransactionResponse An unsigned EIP-1559 transaction ready for the payee to sign.
type PrepareTransactionResponse struct {
	ChainId int `json:"chainId"`
	// ABI-encoded calldata (informational).
	Data string `json:"data"`
	GasLimit Uint256String `json:"gasLimit"`
	MaxFeePerGas Uint256String `json:"maxFeePerGas"`
	MaxPriorityFeePerGas Uint256String `json:"maxPriorityFeePerGas"`
	Nonce int `json:"nonce"`
	// Target contract address (informational).
	To Address `json:"to"`
	// Server-side Transaction row ID. Passed back in the submit body to link the signed tx to the prepare step.
	TransactionId string `json:"transaction_id"`
	// RLP-encoded unsigned EIP-1559 transaction (type 2).
	UnsignedTransaction string `json:"unsigned_transaction"`
}

// RefundPaymentRequest Amount to refund to the payer.
type RefundPaymentRequest struct {
	// Amount to refund (in token base units). Must be > 0 and <= current refundable_amount.
	Amount Uint256String `json:"amount"`
}

// ReleaseRequest Optional parameters for the release prepare step.
type ReleaseRequest struct {
	// Address of the account that will sign and submit the release transaction. Defaults to the payment's `payee` if omitted.
	CallerAddress *Address `json:"caller_address,omitempty"`
}

// SigningPayload EIP-712 typed-data structure that the payer (or payee for refund) must sign. Pass verbatim to `eth_signTypedData_v4`.
type SigningPayload struct {
	Domain EIP712Domain `json:"domain"`
	Message EIP3009Message `json:"message"`
	PrimaryType string `json:"primaryType"`
	Types any `json:"types"`
}

// SubmitTransactionAcceptedResponse Acknowledgement that the transaction has been enqueued. Poll `GET /payments/{rail0_id}` for the final outcome.
type SubmitTransactionAcceptedResponse struct {
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Always `submitting` — the worker has not yet received the on-chain receipt.
	Status string `json:"status"`
}

// SubmitTransactionRequest Signed transaction to broadcast on-chain.
type SubmitTransactionRequest struct {
	// RLP-encoded signed EIP-1559 transaction as returned by `eth_signTransaction`.
	SignedTransaction string `json:"signed_transaction"`
}

// Transaction A blockchain transaction associated with a payment.
type Transaction struct {
	// Protocol fee deducted. `"0"` until confirmed.
	FeeAmount Uint256String `json:"fee_amount"`
	// Smart contract operation executed by this transaction.
	Operation string `json:"operation"`
	// Parent payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// `submitted` = broadcast, awaiting confirmation. `confirmed` = mined successfully. `failed` = reverted.
	Status string `json:"status"`
	// ISO 8601 timestamp when the transaction was broadcast on-chain.
	SubmittedAt string `json:"submitted_at"`
	// Keccak256 hash of the broadcast transaction.
	TransactionHash Bytes32 `json:"transaction_hash"`
	// Token amount processed. `null` until confirmed.
	Amount *Uint256String `json:"amount,omitempty"`
	// Block number in which the transaction was mined. `null` until confirmed.
	BlockNumber *int `json:"block_number,omitempty"`
	// ISO 8601 timestamp when the transaction was confirmed. `null` until confirmed.
	ConfirmedAt string `json:"confirmed_at,omitempty"`
}

// TransactionRecord An on-chain transaction attempt associated with a payment.
type TransactionRecord struct {
	FeeAmount string `json:"fee_amount"`
	Id string `json:"id"`
	Operation string `json:"operation"`
	Status string `json:"status"`
	Amount string `json:"amount,omitempty"`
	BlockNumber *int `json:"block_number,omitempty"`
	ConfirmedAt string `json:"confirmed_at,omitempty"`
	ErrorReason string `json:"error_reason,omitempty"`
	PendingAt string `json:"pending_at,omitempty"`
	SubmittedAt string `json:"submitted_at,omitempty"`
	TransactionHash *Bytes32 `json:"transaction_hash,omitempty"`
}

// WalletToken A wallet token configuration linking a wallet address to a specific token on a chain.
type WalletToken struct {
	Active bool `json:"active"`
	// Ethereum wallet address.
	Address Address `json:"address"`
	ChainId int `json:"chain_id"`
	ChainName string `json:"chain_name"`
	ChainSlug string `json:"chain_slug"`
	Default bool `json:"default"`
	Id string `json:"id"`
	TokenAddress Address `json:"token_address"`
	TokenDecimals int `json:"token_decimals"`
	TokenId string `json:"token_id"`
	TokenSymbol string `json:"token_symbol"`
	WalletId string `json:"wallet_id"`
	Label string `json:"label,omitempty"`
}

// PageMeta holds pagination metadata returned by list endpoints.
type PageMeta struct {
	Page    int `json:"page"`
	PerPage int `json:"per_page"`
	Total   int `json:"total"`
}

// PaginatedResponse is a generic paginated list response.
type PaginatedResponse[T any] struct {
	Data []T      `json:"data"`
	Meta PageMeta `json:"meta"`
}

// WalletToken is a single wallet token entry returned by Accounts.Wallets.
type WalletToken struct {
	ID           string `json:"id"`
	WalletID     string `json:"wallet_id"`
	Address      string `json:"address"`
	Default      bool   `json:"default"`
	Active       bool   `json:"active"`
	TokenID      string `json:"token_id"`
	TokenSymbol  string `json:"token_symbol"`
	TokenAddress string `json:"token_address"`
	TokenDecimals int   `json:"token_decimals"`
	ChainID      int    `json:"chain_id"`
	ChainName    string `json:"chain_name"`
	ChainSlug    string `json:"chain_slug"`
}

// PaymentSummary is the payment object returned by list and get endpoints.
type PaymentSummary struct {
	Rail0ID             string  `json:"rail0_id"`
	Status              string  `json:"status"`
	Mode                string  `json:"mode"`
	Amount              string  `json:"amount"`
	Payer               string  `json:"payer"`
	Payee               string  `json:"payee"`
	Token               string  `json:"token"`
	AuthorizationExpiry int     `json:"authorization_expiry"`
	RefundExpiry        int     `json:"refund_expiry"`
	Metadata            any     `json:"metadata,omitempty"`
	CreatedAt           string  `json:"created_at"`
}

// TransactionRecord is a single on-chain transaction associated with a payment.
type TransactionRecord struct {
	ID              string  `json:"id"`
	Operation       string  `json:"operation"`
	Status          string  `json:"status"`
	TransactionHash *string `json:"transaction_hash,omitempty"`
	Amount          *string `json:"amount,omitempty"`
	FeeAmount       string  `json:"fee_amount"`
	BlockNumber     *int    `json:"block_number,omitempty"`
	ErrorReason     *string `json:"error_reason,omitempty"`
	PendingAt       *string `json:"pending_at,omitempty"`
	SubmittedAt     *string `json:"submitted_at,omitempty"`
	ConfirmedAt     *string `json:"confirmed_at,omitempty"`
}
