// Code generated by gen/generate.go on 2026-05-20 15:42:29 UTC; DO NOT EDIT.
// Source: rail0-api/doc/openapi.json
//
// To regenerate after changing the OpenAPI spec:
//   go run gen/generate.go

package rail0

// Address is a type alias for string. EVM address (checksummed or lowercase hex, 20 bytes).
type Address = string

// Bytes32 is a type alias for string. 32-byte hex value.
type Bytes32 = string

// Uint256String is a type alias for string. Non-negative integer encoded as a decimal string to avoid JSON numeric precision loss.
type Uint256String = string

// ApproveRequest Amount to approve on the token contract. Setting this to the maximum expected refund (or `type(uint256).max` for unlimited) avoids repeated approvals.
type ApproveRequest struct {
	// Allowance to grant the RAIL0 contract (in token base units). Use '115792089237316195423570985008687907853269984665640564039457584007913129639935' for unlimited approval.
	Amount Uint256String `json:"amount"`
}

// ApproveResponse
type ApproveResponse struct {
	// Approved allowance amount.
	Amount Uint256String `json:"amount"`
	// RAIL0 contract address that was approved as spender.
	Spender Address `json:"spender"`
	// Token contract on which the approval was set.
	Token Address `json:"token"`
	// On-chain transaction hash of the `approve()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
}

// AuthorizePaymentResponse
type AuthorizePaymentResponse struct {
	// Amount now held in escrow and available for capture (equals the authorized amount).
	CapturableAmount Uint256String `json:"capturableAmount"`
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// On-chain transaction hash of the `authorize()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
	// Unix timestamp after which capture is no longer possible and release becomes available.
	AuthorizationExpiry *int64 `json:"authorizationExpiry,omitempty"`
}

// CapturePaymentRequest Amount to capture from escrow. May be less than the total capturable balance for a partial capture.
type CapturePaymentRequest struct {
	// Amount to capture (in token base units). Must be > 0 and <= current capturableAmount.
	Amount Uint256String `json:"amount"`
}

// CapturePaymentResponse
type CapturePaymentResponse struct {
	// Remaining escrowed amount still available for future captures.
	CapturableAmount Uint256String `json:"capturableAmount"`
	// Gross amount captured in this call (before fee deduction). Matches the `amount` parameter passed to the contract.
	CapturedAmount Uint256String `json:"capturedAmount"`
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Cumulative amount already captured and eligible for refund (until refundExpiry).
	RefundableAmount Uint256String `json:"refundableAmount"`
	// On-chain transaction hash of the `capture()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
	// Unix timestamp after which further captures are no longer possible.
	AuthorizationExpiry *int64 `json:"authorizationExpiry,omitempty"`
	// Fee deducted from this capture and sent to feeReceiver. '0' when feeBps is 0.
	FeeAmount *Uint256String `json:"feeAmount,omitempty"`
}

// ChargePaymentResponse
type ChargePaymentResponse struct {
	// Gross amount charged (before fee deduction). Matches the `amount` parameter passed to the contract.
	ChargedAmount Uint256String `json:"chargedAmount"`
	// Fee sent to feeReceiver. '0' when feeBps is 0.
	FeeAmount Uint256String `json:"feeAmount"`
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Amount eligible for refund (equals chargedAmount; the full gross amount is tracked as refundable by the contract).
	RefundableAmount Uint256String `json:"refundableAmount"`
	// On-chain transaction hash of the `charge()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
}

// CreatePaymentRequest Parameters needed to create a payment intent. The API generates a unique `paymentId`, applies its fixed policy config, and constructs the EIP-712 signing payload.
type CreatePaymentRequest struct {
	// EVM chain ID of the target network.
	ChainId int `json:"chain_id"`
	Payment PaymentInput `json:"payment"`
	// `authorize` — funds are held in escrow and captured later by the payee. `charge` — one-shot: funds are immediately distributed to payee and feeReceiver with no escrow window. The two modes use different EIP-3009 nonce prefixes; a signature produced for one cannot be submitted for the other.
	Mode string `json:"mode,omitempty"`
}

// CreatePaymentResponse
type CreatePaymentResponse struct {
	// Payment mode: "authorize" or "charge".
	Mode string `json:"mode"`
	// EVM chain ID.
	ChainId int `json:"chain_id"`
	// EIP-712 hash of the Payment struct over the RAIL0 domain. Commits the signature to the exact payment terms.
	ConfigHash Bytes32 `json:"config_hash"`
	Payment PaymentConfig `json:"payment"`
	// Unique identifier for this payment (generated by the API, bytes32 hex).
	Rail0Id Bytes32 `json:"rail0_id"`
	// Address of the RAIL0 contract on the target chain.
	Rail0Contract Address `json:"rail0_contract"`
	SigningPayload SigningPayload `json:"signing_payload"`
}

// EIP3009Message Message fields for the EIP-3009 TransferWithAuthorization typed-data signature.
type EIP3009Message struct {
	// Payer address (token sender).
	From Address `json:"from"`
	// keccak256(NONCE_PREFIX, paymentId, configHash) where NONCE_PREFIX is `RAIL0.AUTHORIZE` for mode=authorize and `RAIL0.CHARGE` for mode=charge. Binds the signature to the exact Payment configuration and operation type.
	Nonce Bytes32 `json:"nonce"`
	// RAIL0 contract address (token recipient / escrow).
	To Address `json:"to"`
	// Always '0' for RAIL0 authorize flows.
	ValidAfter Uint256String `json:"validAfter"`
	// Equals payment.authorizationExpiry (Unix timestamp as string).
	ValidBefore Uint256String `json:"validBefore"`
	// Amount to transfer (same as the requested authorization amount).
	Value Uint256String `json:"value"`
}

// EIP712Domain EIP-712 domain for the token contract (used by EIP-3009 TransferWithAuthorization).
type EIP712Domain struct {
	// EVM chain ID.
	ChainId int `json:"chainId"`
	// Token's EIP-712 domain name.
	Name string `json:"name"`
	// Token contract address.
	VerifyingContract Address `json:"verifyingContract"`
	// Token's EIP-712 domain version.
	Version string `json:"version"`
}

// Error
type Error struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Human-readable error description.
	Message string `json:"message"`
}

// PayerSignatureRequest EIP-712 signature over the `signingPayload` returned by `POST /payments`. Browser wallets return this directly from `eth_signTypedData_v4`; backends produce it with any EIP-712 library. The on-chain verification only checks the recovered address.
type PayerSignatureRequest struct {
	// 65-byte secp256k1 signature in hex (0x-prefixed, 132 chars): r (32 bytes) + s (32 bytes) + v (1 byte). This is the format returned directly by `eth_signTypedData_v4` and all standard Ethereum signing libraries.
	Signature string `json:"signature"`
}

// PayerSignatureResponse
type PayerSignatureResponse struct {
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Confirms the signature was accepted and stored.
	Status string `json:"status"`
	// The address recovered from the signature — should match `payment.payer`. Included for client-side verification.
	RecoveredPayer *Address `json:"recoveredPayer,omitempty"`
}

// PaymentConfig Immutable payment configuration that maps 1-to-1 to the RAIL0 `Payment` Solidity struct.
type PaymentConfig struct {
	// Exact amount the payer commits to pay (in token base units, fits in uint120).
	Amount Uint256String `json:"amount"`
	// Unix timestamp (seconds). Capture must happen before this; release opens after.
	AuthorizationExpiry int64 `json:"authorization_expiry"`
	// Fee in basis points (0 = no fee, 10000 = 100%).
	FeeBps int `json:"fee_bps"`
	// Recipient of the fee on each capture. Use the zero address (0x0000…0000) when feeBps is 0.
	FeeReceiver Address `json:"fee_receiver"`
	// Merchant address. Authorized to capture, void, and refund.
	Payee Address `json:"payee"`
	// Buyer address. Funds are pulled from this address.
	Payer Address `json:"payer"`
	// Unix timestamp (seconds). Refund must happen before this. Must be >= authorizationExpiry.
	RefundExpiry int64 `json:"refund_expiry"`
	// EIP-3009-capable ERC-20 token address (must be accepted by the RAIL0 deployment).
	Token Address `json:"token"`
}

// PaymentInput Buyer-supplied payment parameters sent when creating a payment.
type PaymentInput struct {
	// Amount to pay (in token base units, e.g. "100000000" for 100 USDC with 6 decimals).
	Amount Uint256String `json:"amount"`
	// Merchant wallet address (walletAddress from GET /merchants/{id}/payment-methods).
	Payee Address `json:"payee"`
	// Buyer address. Funds are pulled from this address.
	Payer Address `json:"payer"`
	// ERC-20 token address (tokenAddress from GET /merchants/{id}/payment-methods).
	Token Address `json:"token"`
}

// PaymentMethod A single accepted payment method for a merchant: one (chain, token, wallet) combination.
type PaymentMethod struct {
	// EVM chain ID, derived from the token record.
	ChainId int `json:"chain_id"`
	// Human-readable chain name.
	ChainName string `json:"chain_name"`
	// URL-friendly chain slug (e.g. "arc-testnet", "celo").
	ChainSlug string `json:"chain_slug"`
	// Block explorer URL for this chain.
	ExplorerUrl string `json:"explorer_url"`
	// MERCHANT_WALLETS row identifier.
	Id string `json:"id"`
	// True for the merchant's pre-selected payment method.
	IsDefault bool `json:"default"`
	// ERC-20 token contract address on the chain.
	TokenAddress Address `json:"token_address"`
	// Token decimal places.
	TokenDecimals int `json:"token_decimals"`
	// TOKENS row identifier (tokens.id).
	TokenId string `json:"token_id"`
	// Token ticker symbol.
	TokenSymbol string `json:"token_symbol"`
	// Merchant wallet address to use as `payee` in PaymentConfig.
	WalletAddress Address `json:"wallet_address"`
}

// PrepareTransactionResponse An unsigned EIP-1559 transaction ready for the payee to sign. Signing options: (a) wallet users pass `unsignedTransaction` to `eth_signTransaction`; (b) backends with direct key access sign the RLP blob with any secp256k1 library (e.g. `wallet.signTransaction` in ethers.js). Submit the resulting signed RLP to the corresponding `/submit` endpoint.
type PrepareTransactionResponse struct {
	// EVM chain ID.
	ChainId int `json:"chain_id"`
	// ABI-encoded calldata (informational; already encoded in `unsignedTransaction`).
	Data string `json:"data"`
	// Estimated gas limit with a safety margin.
	GasLimit int64 `json:"gasLimit"`
	// EIP-1559 max fee per gas (wei).
	MaxFeePerGas int64 `json:"maxFeePerGas"`
	// EIP-1559 max priority fee per gas (wei).
	MaxPriorityFeePerGas int64 `json:"maxPriorityFeePerGas"`
	// Transaction nonce for the payee's account.
	Nonce int `json:"nonce"`
	// RAIL0 contract address (informational; already encoded in `unsignedTransaction`).
	To Address `json:"to"`
	// RLP-encoded unsigned EIP-1559 transaction (type 2). Pass to `eth_signTransaction` (browser wallet) or sign directly with a secp256k1 library if the key is available in-process.
	UnsignedTransaction string `json:"unsigned_transaction"`
}

// RefundPaymentRequest Amount to refund to the payer. Must be > 0 and <= current refundableAmount.
type RefundPaymentRequest struct {
	// Amount to refund (in token base units). Must be > 0 and <= current refundableAmount.
	Amount Uint256String `json:"amount"`
}

// RefundPaymentResponse
type RefundPaymentResponse struct {
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Remaining refundable balance after this refund.
	RefundableAmount Uint256String `json:"refundableAmount"`
	// Amount refunded to the payer in this call.
	RefundedAmount Uint256String `json:"refundedAmount"`
	// On-chain transaction hash of the `refund()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
}

// ReleasePaymentResponse
type ReleasePaymentResponse struct {
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Amount returned to the payer (was the full remaining capturableAmount).
	ReleasedAmount Uint256String `json:"releasedAmount"`
	// On-chain transaction hash of the `release()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
}

// SigningPayload EIP-712 typed-data structure that the payer must sign. The `domain`, `types`, and `message` fields follow the EIP-712 standard. Signing options: (a) wallet users pass this object verbatim to `eth_signTypedData_v4`; (b) backends with direct key access compute `keccak256('\x19\x01' || domainSeparator || hashStruct(message))` with any EIP-712 library and sign with secp256k1. Both approaches produce the same 65-byte signature to submit to `PUT /payments/{paymentId}/sign`.
type SigningPayload struct {
	Domain EIP712Domain `json:"domain"`
	Message EIP3009Message `json:"message"`
	// EIP-712 primary type.
	PrimaryType string `json:"primaryType"`
	// EIP-712 type definitions.
	Types any `json:"types"`
}

// SubmitTransactionRequest Signed transaction to submit on-chain.
type SubmitTransactionRequest struct {
	// RLP-encoded signed EIP-1559 transaction as returned by `eth_signTransaction`.
	SignedTransaction string `json:"signed_transaction"`
}

// VoidPaymentResponse
type VoidPaymentResponse struct {
	// Payment identifier.
	Rail0Id Bytes32 `json:"rail0_id"`
	// Amount returned to the payer (was the full capturableAmount).
	ReleasedAmount Uint256String `json:"releasedAmount"`
	// On-chain transaction hash of the `void()` call.
	TransactionHash Bytes32 `json:"transactionHash"`
}
